### DISCUSSION TITLE
flyway 적용기

### DISCUSSION THREAD

**Discussion by hyeonji1220** [woowacourse-teams/2024-review-me#798] [문서화]
# 해결하고 싶은 문제
운영 db에 변경사항을 반영하기 전에 개발 db에서 변경 사항을 미리 적용해보고 추후 운영 db에 적용하는데, 이 때 개발 db에서 어떤 변경 사항을 적용했는지 관리하고 싶다.
→  DB 관련 어떤 변화가 있었는지 Git 처럼 형상 관리를 하고싶다.

# 우리 팀 상황
기존 데이터베이스에 테이블과 유저 데이터가 있는 상황. 따라서 이미 db에 테이블이 들어가있어서 V1 파일이 init.sql일 수 없다.
- 비어있는 DB라면 V1__init.sql 파일부터 flyway 대상 패키지에 넣으면 알아서 테이블 만들어줬을 것.
- 하지만 우리는 이미 테이블, 유저 데이터가 있는 상황.
- 그렇다면 기존 데이터를 어떻게 flyway가 최초 버전으로 인식하게 하지?
	- baseline을 활용하면 현재 우리의 데이터베이스를 ver 0으로 인식하게 할 수 있다.
- 그렇다면 V1__first_change.sql이 첫번째 파일이 될텐데, init.sql 파일이 명시되지 않는 문제가 발생함.
	- init.sql 즉, 초기 스키마 설정 파일은 schema.sql로 따로 명시해놓고 이후 최초 변경사항을 V1 문서로 관리한다.

# 과정
1. 의존성 추가
```gradle
implementation 'org.flywaydb:flyway-core'  
implementation 'org.flywaydb:flyway-mysql'
```

2. application.yml 설정
- baseline-on-migrate: 기존 DB에 테이블이 있는 경우 그걸 baseline으로 하겠다. 
- baseline-version: 위의 기존 baseline 버전을 0으로 설정하겠다.
```yml
spring: 
    flyway:  
        enabled: true  
        baseline-on-migrate: true  
        baseline-version: 0  
        url: jdbc:mysql://localhost:3306/databaseName
        user: root  
        password: 1234
```

3. V1 마이그레이션 스크립트 생성
   - 네이밍 컨벤션 V__버전숫자_파일이름.sql
   - 원래라면 init.sql이었겠지만 우리는 기존 스키마가 있어서 변경사항만.
```sql
-- 예시
ALTER TABLE reservation_time ADD COLUMN position INT DEFAULT 0;
```
4. (sql문 추가시 관련된) 엔티티 변경

# 주의점
1. sql문에 에러가 있더라도 flywa_schema_history 테이블에 해당 버전의 sql이 추가가 된다. 이럴 경우 db에서 해당 버전 row를 직접 삭제해주고 해당 버전의 sql 파일을 다시 만들어야한다.
2. 엔티티 변경과 그에 대응하는 sql문 작성이 항상 함께 가야합니다.

# flyway가 db 적용되는 시점은 언제일까?
- **애플리케이션 시작 시점**: Flyway는 애플리케이션이 시작될 때, 즉 JVM이 시작되고 스프링 컨텍스트가 로드되기 전에 마이그레이션을 수행합니다.
- **마이그레이션 수행**: Flyway는 데이터베이스에 연결하여 정의된 SQL 마이그레이션 파일을 실행합니다. 이 과정은 애플리케이션의 실행 중에 발생하며, 애플리케이션 코드가 데이터베이스와 상호작용하기 전에 완료되어야 합니다.
