### DISCUSSION TITLE
무중단 배포 작업 결과

### DISCUSSION THREAD

**Discussion by hyeonji1220** [woowacourse-teams/2024-review-me#899] [문서화]
## 문제 상황
CD를 통해 배포하는 과정에서, 어플리케이션을 down하고 다시 up하는 동안 down time이 발생한다.
이 시간 동안 사용자는 서비스를 이용할 수 없다.

## 목표
배포를 하는 중에도 down time이 생기지 않게한다.

**Comment by hyeonji1220** [comment]
# 어떤 무중단 배포 전략을 선택할까?

## 방식 후보
### Rolling 방식
서버 A, B, C 가 있다 할 때, 
1/ 서버 A로 오는 트래픽을 끊고, A 를 업데이트 한다.
2/ 서버 A의 업데이트가 끝나면, A 로의 트래픽을 재개한다.
3/ 이 과정에서 A(new), B(old), C(old)의 상태가 되고, B와 C에도 이를 반복한다. 

단점: 
\- 배포하는 동안 서비스 전체가 받을 수 있는 트래픽이 줄어들게 된다. 
\- 3대 이상인 경우, 다른 API 명세를 가진 서버가 동시에 존재하는 문제가 발생할 수 있다. 

<img width="394" alt="image" src="https://github.com/user-attachments/assets/d3730091-bc11-4adf-8168-30c2d3292725">

---

### Blue-Green 방식

기존 어플리케이션을 Blue, 새로운 어플리케이션을 Green 이라고 할 때,
1/ Blue에서 정상적으로 트래픽을 받고 있는 상태에서, 새로운 버전의 어플리케이션 Green을 실행한다.
2/ Green 이 정상적으로 실행되는 것이 확인되면, Blue 로 가던 트래픽을 끊고 Green 으로 가게 한다.
3/ 이후 Blue 를 제거한다.

단점: 
\- 배포하는 동안은 한 인스턴스에 2개의 어플리케이션이 떠있으므로 CPU, 메모리에 부담이 있을 수 있다.
\- 따라서 응답 속도도 안 좋아질 수 있다.

<img width="394" alt="image" src="https://github.com/user-attachments/assets/22147834-249c-4ba6-a52e-f429e2624cfe">

---

## 최종 결정: Blue-Green 방식

배포 순간에 두 단점을 비교해보았을 때, Rolling 방식의 단점이 더 크게 다가왔다.
Rolling 방식을 진행하는 도중에는, 서로 다른 두개의 API 가 존재하는 순간이 있을 수 있다.
또한 특정 서버가 업데이트 되는 동안은 거기로 향하는 트래픽을 끊기 때문에,
트래픽의 분산의 원활이 일어나지 않아 부하가 일어날 수도 있다고 생각했다.
이러한 이유로, 최종적으로 Blue-Green 방식을 선택하게 되었다.

**Comment by hyeonji1220** [comment]
## 🧑🏻‍⚖️ 우리는 왜 [Code Deploy의 블루 그린] 방법을 사용하지 않았는가?

### Code Deploy의 블루 그린 방식을 고려했던 이유
- code deploy 의 블루 그린 방식을 사용하면 ec2를 삭제하고, 새로운 jar 파일이 담긴 ec2 를 생성해준다.
- ec2에 들어가서 작업하는게 불편하다 느꼈던 우리 팀은 항상 'ec2 상수화'를 고대했었는데, 블루 그린 방식은 이런 우리 팀의 니즈와 잘 맞아 보였다.

### 한계
- 하지만, ec2 를 삭제하고 새로 생성하는 것은 많은 사이드 이펙트를 야기했다.
- 일례로 우리 팀은 프로메테우스로 각 ec2 의 메트릭을 받아오고 있었다. 그리고 프로메테우스는 `pull` 방식이므로 `target-ip`를 알고 있어야 했다. 이런 모니터링 전략은 '변하지 않는 ip'가 전제되어야 했으므로, ec2 를 삭제-생성하는 code deploy의 블루그린 방식과 맞지 않았다.
- 물론 이를 [해결할 수 있는 방법](https://prometheus.io/docs/prometheus/latest/http_sd/
)이 있다고는 하지만, 이를 위해서는 우리의 지금 목표인 '무중단 배포'보다 더 큰 작업이 필요할 것 같았다.

### 느낀 점
- Code Deploy의 블루 그린 방식을 고려하면서, 우리의 서비스는 '스케일 아웃 or 오토 스케일링'이 힘든 구조라는 것을 알게 되었다.
- 이 부분을 문제라고 느꼈으며, 추후 이를 보완할 수 있는 방법들을 찾아보기로 했다.
- 이것을 알게 되었다는 것 만으로도 의미가 있었던 삽질이라는 생각이 든다.

**Comment by hyeonji1220** [comment]
# 변경 1. github-actions에서 배포 방식 변경

### AS-IS
도커에서 바로 이미지를 다운로드해서 컨테이너를 실행
```yml
      - name: Pull from DockerHub
        run: |
          sudo docker-compose --env-file .env.dev down || true
          sudo docker pull ${{ secrets.DOCKERHUB_ID }}/review-me-app:develop
          sudo docker-compose --env-file .env.dev up -d
        working-directory: ${{ env.APPLICATION_DIRECTORY }}/app
```

### TO-BE
실행 환경(dev/prod)을 변수로 전달하여 배포 스크립트 실행

```yml
      - name: Deploy new version
        env:
          PROFILE_VAR: "dev"
        run: |
          chmod +x ./deploy.sh
          sudo -E ./deploy.sh

        working-directory: ${{ env.APPLICATION_DIRECTORY }}/app
```

**Comment by hyeonji1220** [comment]
# 변경2. [배포 스크립트](https://github.com/woowacourse-teams/2024-review-me-secret/blob/develop/app/deploy.sh) 추가

1. 현재 실행중인 포트를 확인하고, 새로 배포할 포트를 결정

    예: 현재 어플리케이션이 실행중인 포트가 8080이라면, 새로 배포할 포트는 8081

2. iptable에 기존의 포트로 포트 포워딩하는 규칙 추가
새로운 어플리케이션이 실행이 되었을 때 
아직 그 어플리케이션이 healthy 한 상태가 아님에도 그쪽으로 트래픽이 가는 상황을 방지하기 위함임
```bash
# 기존 활성화된 포트로 포워딩 유지 ( 80 → 8080 )
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port $CURRENT_PORT
```
위의 명령어로 기존 실행중인 어플리케이션으로 요청이 가도록 강제해놓았기 때문에, 
새로운 배포가 적용된 어플리케이션의 컨테이너를 실행은 하나 요청이 가지는 않는다.

3. 새로운 버전의 어플리케이션 컨테이너 실행 시키기

4. 새로운 버전의 어플리케이션 헬스 체크

4. 새로운 버전의 어플리케이션 healthy가 확인되면, 해당 어플리케이션으로 요청이 가도록 포트 포워딩  ( 80 → 8081 )

5. 이전 어플리케이션 컨테이너 down

**Comment by hyeonji1220** [comment]
# 변경 3. docker-compose 설정 변경
실행될 어플리케이션의 application.yml에 SERVER_PORT, ACTUATOR_PORT를 다르게 주입해줘야한다. 
따라서 docker-compose.yml에서 두 포트 정보를 environment로 선언해 application.yml에 주입해준다.

```yml
services:
  app-8080: # 8080 포트로 실행되는 스프링 어플리케이션 서비스
    image: reviewme/review-me-app:${DOCKER_TAG}
    container_name: review-me-app-8080
    ports:
      - "8080:8080"
      - "5959:5959"
    volumes:
      - ./application-${SPRING_PROFILE}.yml:/application.yml
      - /home/ubuntu/logs/:/logs
    environment:
      - SERVER_PORT=8080 # application.yml에 주입될 변수
      - ACTUATOR_PORT=5959 
      - TZ=Asia/Seoul

  app-8081: # 8081 포트로 실행되는 스프링 어플리케이션 서비스
    image: reviewme/review-me-app:${DOCKER_TAG}
    container_name: review-me-app-8081
    ports:
      - "8081:8081"
      - "5960:5960"
    volumes:
      - ./application-${SPRING_PROFILE}.yml:/application.yml
      - /home/ubuntu/logs/:/logs
    environment:
      - SERVER_PORT=8081  
      - ACTUATOR_PORT=5960 
      - TZ=Asia/Seoul
```

**Comment by hyeonji1220** [comment]
# 변경 4. application.yml 설정 변경

docker-compose.yml에서 주입받은 SERVER_PORT(8080 OR 8081)로 스프링 어플리케이션을 띄우도록 한다. (헬스체크를 위한 포트(5959 OR 5960)도 함께 주입, 설정). 
이를 위해 application.yml에 해당 환경 변수를 넣어준다. 이 때, ports 정보를 관리하는 yml을 분리하여 application.yml에 import한다.

```yml
// application-dev.yml

spring:
  profiles:
    active: dev

  config:
    import:
      - classpath:ports.yml
```

```yml
// ports.yml

server:
  port: ${SERVER_PORT}

management:
  server:
    port: ${ACTUATOR_PORT}
```

**Comment by hyeonji1220** [comment]
# 무중단 배포 결과 확인

**Reply by hyeonji1220** [reply]
## 1. `무중단`인지
배포를 하면서 동시에, 
1초에 300번의 리뷰폼 질문 가져오기 요청(GET)을 보낼 때 오류 처리되는 요청이 있는지 확인.
(방법: jmeter로 100개의 쓰레드가 1초에 3개씩 보냄)

### 결과
1. 오류 처리되는 요청 없음
![image](https://github.com/user-attachments/assets/d5b347c5-a229-4ef5-add1-89ec604353ea)

2. deploy step: 배포 스크립트 실행 자체에 43초 걸렸고,  정상 종료

<img width="871" alt="스크린샷 2024-10-22 오후 4 17 27" src="https://github.com/user-attachments/assets/03be3bc1-123d-4460-b7df-af1f442a3df1">

**Reply by hyeonji1220** [reply]
## 2. 부하가 크지 않은지

- 평소 상태
CPU: 4%
ram: 80%
![image](https://github.com/user-attachments/assets/98a528cb-433d-4d60-b528-c6890f527e63)

### 1. 배포만 할 때: 기존 스프링 어플리케이션 + 배포(CD)
1. 견디는가?: 견딘다. ec2가 죽지 않았다.
2. CPU: CD 과정 동안 %에 도달했다.
3. ram: %에 도달했다.



### 2. 요청도 같이 보낼 때: 기존 스프링 어플리케이션 + 배포(CD) + 1초당 10회 GET 요청 보내는 상황 
- 요청 상황: 1초에 10개씩 리뷰폼 질문 가져오기 요청

1. 견디는가?: 견딘다.
2. CPU: CD 과정 동안 80%에 도달했다.
3. ram: 90%에 도달했다.🤒

![image](https://github.com/user-attachments/assets/9f6a7e9b-9d39-4e4b-8002-a6cf23c33daf)

**Comment by hyeonji1220** [comment]
# 운영 서버: 수동 배포 방식으로 변경

개발 서버의 배포는 '자동'으로 develop 브랜치에 머지가 될 때 진행됩니다.
운영 서버의 배포는 '수동'으로, 직접 run을 해줘야 진행됩니다.
이렇게 차이를 둔 이유는 다음과 같습니다.

블루 그린 방식은 순간적으로 하나의 EC2에 두개의 어플리케이션이 뜨므로, TPS가 떨어집니다.
이 영향을 최소화하는 방법을 '새벽 배포'같은 것들이 있을거라 생각이 들어 운영 서버 배포는 수동으로 해주었습니다.
하지만 개발 서버는 이러한 것들을 신경쓰지 않아도 되므로 자동으로 해줬습니다.

**Comment by hyeonji1220** [comment]
# 현재 방식에서 발생할 수 있는 문제

현재 actions runner는 default가 병렬로 실행하게 되어있어요. 하지만 두 runner가 실행될 때 약간의 시간 차이(수치 추가)가 있어서 이로 인한 구-신버전이 짧은 시간 공존하는 문제가 생길 수 있어요

<img width="595" alt="image" src="https://github.com/user-attachments/assets/47e924af-a3be-4f54-af02-c738535b2130">

```yml
  deploy:
    name: Deploy via self-hosted runner
    needs: build
    strategy:
      matrix:
        runner: [prod-a, prod-b]
    runs-on: [ self-hosted, "${{ matrix.runner }}" ]

```

### 방안 1. prod1 서버에서 배포가 진행되는 동안 prod2 서버에 요청이 가지 못하게 한다
prod2의 배포 준비가 다 되면 그 때 연결한다. 
단점은, 이 시간 동안 모든 요청을 prod 1이 받게된다.
