### ISSUE TITLE
[BE] 로컬에서 어플리케이션이 동작하게 한다.

### ISSUE THREAD

**Issue by nayonsoso** [woowacourse-teams/2024-review-me#1046]
### 🔍 설명
- https://github.com/woowacourse-teams/2024-review-me/pull/1010 에서 H2 의존성이 testRuntimeOnly 으로 바뀌었습니다.
- 그런데 로컬에서 실행할 때 H2를 사용하므로, 지금 로컬에서 어플리케이션이 실행이 안됩니다.
- 이를 해결하기 위한 두가지 방법을 생각해봤어요.

**1/ 로컬에서 mysql 쓰도록 application.yml 을 아래와 같이 변경**
```yml
# IS-AS
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
```

```yml
# TO-BE
  datasource:  
    driver-class-name: com.mysql.cj.jdbc.Driver  
    url: jdbc:mysql://localhost/review_me?createDatabaseIfNotExist=true&&rewriteBatchedStatements=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8  
    username: {모든 팀원들 컴퓨터에서 같은 이름의 어떤 유저 만들고 권한을 준 다음, 그 유저 이름 사용}  
    password: {그 유저 비밀번호 사용}
```

**2/ build.gradle에 아래 내용 추가**
```groovy
def activeProfile = def activeProfile = project.findProperty("profile") ?: 'local'

dependencies {
    if (activeProfile == 'local') {
        implementation 'com.h2database:h2'
    } else {
        testImplementation 'com.h2database:h2'
    }
}
```

### 🔥 할 일
- 의견을 모으고, PR을 만든다.

### ⏰ 예상 시간
- 5분
